ModAssistant/MainWindow.xaml.cs
ModAssistant/Pages/Mods.xaml.cs

#44 Prevent user from clicking Mod Info without selecting a mod first

---

ModAssistant/Classes/Mod.cs
ModAssistant/Localisation/en.xaml
ModAssistant/Pages/Mods.xaml.cs

**Changes**
- Add "status" to Mod object
- Check if mod wasn't declined before checking if any of it's file hashes match installed files.
- Clarify "Check Installed Mods" -> "Detect Installed Mods". (This was confusing since selected mods are shown a *check*mark.)
**Details**
When detecting installed mods, Mod Assistant checks all possible mod related files in the Beat Saber directory against all files returned by the Beat Mods API.
Occasionally mods get uploaded to Beat Mods containing extra files that aren't supposed to be there, and these mods get declined. However, the Beat Mods API returns every upload in the db. Even mods that were "declined" for having invalid folder structures. 
This could cause Mod Assistant to think that `Custom Notes` was installed if there was a declined …

Quick fix for incorrect mods showing as "installed"

---

ModAssistant/App.xaml.cs

This is a slight modification of the fix in #83 
I looked into it a bit and found this discussion <https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5/36454717#36454717>
To my understanding, instead of setting a strict security protocol, this enables the TLS 1.2 protocol, while leaving the system default enabled as well.
Closes #67

Enable TLS 1.2 security protocol

---

ModAssistant/Pages/Mods.xaml.cs

This should fix MA crashing when a mod has an semver value, like in the screenshot below.
Tested by simply changing the parsed "value" to invalid semver values.

Handle invalid semver from beatmods

---

ModAssistant/MainWindow.xaml.cs

This should fix Mod Assistant not closing when the main window is closed.
I imagine most people didn't even notice this because MA has such a small footprint.

Force shutdown app when main window closed

---

ModAssistant/App.config
ModAssistant/App.xaml.cs
ModAssistant/Classes/Languages.cs
ModAssistant/Classes/Utils.cs
ModAssistant/MainWindow.xaml.cs
ModAssistant/ModAssistant.csproj
ModAssistant/Pages/Options.xaml
ModAssistant/Pages/Options.xaml.cs
ModAssistant/Properties/Settings.Designer.cs
ModAssistant/Properties/Settings.settings

New features
- Language select box in the Options menu that lets you set the UI language.
- New "Languages" class based off of the "Themes" class for handling language loading.
- Selected language is saved and loaded on startup. If no saved language is detected, it loads the system language. If the system language isn't supported, it loads English instead.
Thankfully the UI seems to completely refresh when the language is changed, so this PR mostly has to do with selecting the language.
TODO:
- Figure out where to put the dropdown box in the UI. It's getting pretty cramped.
- Get list of language files in the `Localizations` folder instead of using a hardcoded array. I spent about an hour trying to figure this out, but since the language files are stored inside the executable and accessed …

Language select

---

ModAssistant/MainWindow.xaml
ModAssistant/Pages/About.xaml
ModAssistant/Pages/Intro.xaml

This should fix button text not fitting inside of buttons for certain languages.
I did this by making the button and column widths adjust automatically while observing a minimum width. Unfortunately for the sidebar buttons, I had to scale the text if it was too wide, which makes it a bit difficult to read.
Fixed:
- Sidebar buttons
- Intro accept / decline buttons
- Install / Mod Info buttons
- Headpats / Hugs buttons

Fix text not fitting inside buttons

---

ModAssistant/Classes/Themes.cs

When launching the application from Visual Studio (in the `Debug` configuration), multiple `NullReferenceException`s are thrown as a result of an attempt to access manifest resource streams that do not exist (twice for each of the built-in themes, it would seem).
These exceptions are thrown inside of a `try`/`catch` block, so they do not pose issues to end-users.
However, in the default configuration of Visual Studio 2019 the debugger will break on many types of exceptions, regardless of whether they have been handled or not.  While this behavior can be disabled (<kbd>Debug</kbd> &raquo; <kbd>Windows</kbd> &raquo; <kbd>Exception Settings</kbd> &raquo; Uncheck "Common Language Runtime Exceptions"), a novice may not understand how to do this, and also may not realize that they can simply …

Don't attempt to access non-existent manifest resources

---

ModAssistant/Classes/Utils.cs
ModAssistant/Pages/Mods.xaml.cs
ModAssistant/Pages/Options.xaml.cs

The Clipboard is a shared system resource and thus can only be accessed by a single application at any given moment.  While an application is accessing the clipboard, any attempts made by another application will fail.
Since most operations involving the clipboard are initiated by the user (e.g. copy/paste), and because the user can only have a single window active at any given time, it is unlikely for multiple applications to access the clipboard concurrently.
One such scenario may occur when using Remote Desktop to connect to a remote machine while sharing your clipboard.  This causes the clipboard contents to be synchronized between the local and remote machines, and this has the occasional side-effect of locking the clipboard for extended periods of time.
In fact, the reference source …

Suppress exceptions when setting clipboard data

---

ModAssistant/Localisation/de.xaml
ModAssistant/Localisation/en-DEBUG.xaml
ModAssistant/Localisation/en.xaml
ModAssistant/Localisation/fr.xaml
ModAssistant/Localisation/it.xaml
ModAssistant/Localisation/ko.xaml
ModAssistant/Localisation/nl.xaml
ModAssistant/Localisation/ru.xaml
ModAssistant/Localisation/sv.xaml
ModAssistant/Localisation/zh.xaml
ModAssistant/Pages/Mods.xaml
ModAssistant/Pages/Mods.xaml.cs

Currently there is no text indicating that no mods were found when there are 0 updated mods on beatmods - only an empty mod list is displayed. This has caused a lot of confusion amongst users who believe this is an issue w/ MA. 
(This fixes #71)

Add informative text for versions with no updated mods

---

ModAssistant/Localisation/nl.xaml

Noticed the dutch translations use `U` for `you`, but the capital version is used to refer to deities. Lowercase `u` is a correct translation of `you`. Although I'd prefer using the informal `jij`/`je` however I'm unsure if that overhaul is agreed upon by everyone.
While fixing the `U`'s I've discovered several typos as well as suboptimal translations, likely the result of translating the english texts word for word instead of translating the full sentence to an equal meaning dutch sentence.
Also translated the missing strings.

Add missing NL translations, fix typos and suboptimal NL translations

---

ModAssistant/MainWindow.xaml.cs

A quick hotglue fix for the Issue #239 
Seemed like the code threw an error when the version key wasn't found in the dictionary, so I did a silent if-statement to pass any versions that doesn't match the current one.

Issue #239: Quick hotfix for error that comes if not up-to-date

---

ModAssistant/Localisation/de.xaml
ModAssistant/Localisation/en-DEBUG.xaml
ModAssistant/Localisation/en.xaml
ModAssistant/Localisation/fr.xaml
ModAssistant/Localisation/it.xaml
ModAssistant/Localisation/ko.xaml
ModAssistant/Localisation/nl.xaml
ModAssistant/Localisation/ru.xaml
ModAssistant/Localisation/sv.xaml
ModAssistant/Localisation/zh.xaml
ModAssistant/Pages/Mods.xaml.cs

Simple check if IPA.exe and IPA Directory exists before trying to delete it. This should prevent crashes. Closes #72

Added check and Warning for Uninstalling BSIPA

---

ModAssistant/App.xaml.cs
ModAssistant/Classes/OneClickInstaller.cs
ModAssistant/Pages/Options.xaml.cs

Adds a description to protocol handler registry keys when setting up OneClick install.

Add description for OneClick registry keys

---

ModAssistant/Pages/Mods.xaml.cs

This ensures that MA will detect an installed library only if both the `.manifest` and the `.dll` were found. As it is now, it is checking both separately, and will still add the library if either of them is found.
This solves an issue that can happen if you have clean installed your game, and copied your old Plugins folder with the manifests into your new installation. MA thinks the libraries are installed, while they don't exist in `Libs\`. This can also *maybe* solve the Ini Parser issue that happens sometimes.

Fix libraries detection

---

ModAssistant/Classes/Utils.cs
ModAssistant/Pages/Mods.xaml.cs

This adds an integrity check before extracting the archives downloaded from BeatMods. If the integrity check isn't passed, then we don't extract anything and just redownload the mod again. Tell me if you see any issues.

Add integrity check before file extraction

---

ModAssistant/Pages/Mods.xaml.cs

I was about to become crazy due to this, on some cultures BSIPA ends into `IPA\Pending` due to `mod.name.ToLower() == "bsipa"` not correctly matching. See https://stackoverflow.com/a/19778131 for details.
We replace all `ToLower` to `ToLowerInvariant` to prevent future similar hair-pulling issues.

Use ToLowerInvariant instead of ToLower

---

ModAssistant/Pages/Mods.xaml.cs

Since BeatSaverDownloader is checked by default, I think it would make sense to have ModelDownloader as a default mod too.
This PR simply adds `ModelDownloader` to the `DefaultMods` List in` Mods.xaml.cs`

Added ModelDownloader to the default mods list to go along with BeatSaverDownloader

---

ModAssistant/Classes/External Interfaces/BeatSaver.cs

Switched to new BeatSaver/beatmaps.io API. I've tested it with both playlists and oneclick install and it seems to work fine.
If you need to test before beatsaver goes live, switch out the `BeatSaverURLPrefix ` with `https://api.beatmaps.io` - make sure to replace `beatsaver.com` with `beatmaps.io`  in the downloadURL too if the CDN isn't live yet.

Switch the Playlist and OneClick Install systems to the New BeatSaver API

---

ModAssistant/Pages/Mods.xaml.cs

The Survey mod no longer exists, so it shouldn't be included in the default checked mods.

Remove Survey mod from list of default checked mods

---

ModAssistant/Classes/External Interfaces/BeatSaver.cs

Since people can now download WIP (not published) songs by a direct id, it creates several issues like:
- WIP songs are saved in the same folder as regular songs, so they are mixed together
- a user can still launch the map and create a new leaderboard on ScoreSaber when only the Practice button is usually enabled for WIP songs
This request is based on a version state data and may be rejected if BeatSaver will provide a separated link for WIP maps so it will be process more clearly by OneClick.

On OneClick save WIP song to CustomWIPLevels directory

---

ModAssistant/Classes/External Interfaces/Playlists.cs
ModAssistant/Classes/External Interfaces/Utils.cs
ModAssistant/Classes/Updater.cs
ModAssistant/Classes/Utils.cs

When downloading playlists (and previously zips) from beatsaver the last url segment is not always the best name for the downloaded file. BeatSaver provides a header with both of these that suggests a name for the downloaded file. In the case of maps this is "{map key} ({song name} - {artist name}).zip" and for playlists it is "BeatSaver - {playlist name}.bplist"
This PR will prefer the server's suggestion for **playlists** which should result in the top file being created:
This is not intended to alter anything but the naming

Name downloaded playlists by Content-Disposition

---

README.md

This moves the images in the README directly onto the bsmg github instead of an external CDN.

Host README images on github

---

ModAssistant/Classes/Updater.cs
ModAssistant/Localisation/cs.xaml
ModAssistant/Localisation/de.xaml
ModAssistant/Localisation/en.xaml
ModAssistant/Localisation/es.xaml
ModAssistant/Localisation/fr.xaml
ModAssistant/Localisation/it.xaml
ModAssistant/Localisation/ja.xaml
ModAssistant/Localisation/ko.xaml
ModAssistant/Localisation/nb.xaml
ModAssistant/Localisation/nl.xaml
ModAssistant/Localisation/pl.xaml
ModAssistant/Localisation/pt.xaml
ModAssistant/Localisation/ru.xaml
ModAssistant/Localisation/sv.xaml
ModAssistant/Localisation/th.xaml
ModAssistant/Localisation/zh.xaml
README.md

- Changes the update check URL to use `bsmg` now that ModAssistant is under the bsmg account.
- Fixed any links within the README to point to the `bsmg` repo
- Fixed the Patreon link in the About page. Patreon was already redirecting it automatically anyway.
The updater seemed to work using the old URL, but future releases (if any) need to pull from the correct repo.
For sanity I double checked the downloader by forcing the app version lower, and the app is capable of downloading the latest release from the bsmg repo.
I had to make a different PR to change the README images to make sure they were hosted under the bsmg account instead of my account. #529

Update ModAssistant repo for bsmg account

---

ModAssistant/Classes/Utils.cs
ModAssistant/Pages/About.xaml.cs

Fixes the headpats & pats buttons in the about menu by switching to the api provided by https://waifu.pics/

Fix Pats & Headpats buttons in About menu
