bsmg/ModAssistant

- ModAssistant/Classes/OneClickInstaller.cs
Fix for Issue: https://github.com/Assistant/ModAssistant/issues/5 aka Unhandled exception with OneClick on BeatSaver
> MA-5 #comment set BeatSaver Uri from Segments to Host.

- ModAssistant/Pages/Mods.xaml.cs
> Fix always downloading Steam version of mod

- ModAssistant/Localisation/zh.xaml
- ModAssistant/ModAssistant.csproj
- ModAssistant/Pages/Mods.xaml.cs
( cd47496 Update Mods.xaml.cs is because I haven't learned how to fork a project as a new branch, so I edit the file on the webpage to implement the fork as a new branch. )
> Add Chinese language file

- ModAssistant/Classes/OneClickInstaller.cs
Feel free to make any changes you might see fit.
> Add support for custom bloqs from ModelSaber

- ModAssistant/Pages/Options.xaml.cs
> Remove modsaber link from Options C# file

- ModAssistant/Localisation/en.xaml
- ModAssistant/Pages/Options.xaml.cs
This would solve one of the issues I DM'd you about if the folder doesn't exist.
> Add 'if' and 'else' to Open AppData Button

- ModAssistant/Localisation/nl.xaml
Did my best to translate everything as well as I could
Should probably have been sleeping tbh, it's 2 am and I am here making a localisation file....
> Created dutch localistation file

- ModAssistant/Localisation/fr.xaml
Translated terms in French
Also Wiki links redirect to French pages
> French localisation

- ModAssistant/Localisation/de.xaml
German translation for Mod Assisstant
Might need verification and review
> German localisation

- ModAssistant/Localisation/ko.xaml
> Korean Localization

- ModAssistant/Localisation/fr.xaml
Quickly translated the 6 new strings in FR
> French localisation update

- ModAssistant/Localisation/nl.xaml
> fixed some typos

- ModAssistant/Localisation/it.xaml
> Italian localisation | updated

- ModAssistant/Localisation/en-DEBUG.xaml
- ModAssistant/Localisation/en.xaml
- ModAssistant/Pages/Options.xaml
- ModAssistant/Pages/Options.xaml.cs
> Add the OneClick UI for Playlists

- ModAssistant/Localisation/de.xaml
I translated the remaining phrases
> Updated German Translation

- ModAssistant/Localisation/de.xaml
Had some typos the where actual german words so spell checker didn't catch them and i did overlook them when proof reading
> Fixed typos

- ModAssistant/Pages/Options.xaml
> Move OneClick options into a menu

- ModAssistant/Localisation/fr.xaml
> FR localisation update

- ModAssistant/Localisation/zh.xaml
“我们发现 围城 的网站未经作者同意擅自打包贩卖歌曲、模型，并抹黑社区中的成员。
请各位玩家引以为鉴，不要攻击其他玩家或支持这种行为，谢谢配合。”
> Add description for 围城 event

- ModAssistant/Classes/Utils.cs
> Add exclusion for desktop.ini to anti-piracy

- ModAssistant/Localisation/nl.xaml
they were not entirely correct, or just sounded weird
> Improved some phrases

- ModAssistant/Localisation/de.xaml
- ModAssistant/Localisation/en-DEBUG.xaml
- ModAssistant/Localisation/fr.xaml
- ModAssistant/Localisation/it.xaml
- ModAssistant/Localisation/ko.xaml
- ModAssistant/Localisation/nl.xaml
- ModAssistant/Localisation/ru.xaml
- ModAssistant/Localisation/sv.xaml
- tools/README.md
- tools/generate_translation_stubs.py
Python script to generate translation stubs. Does not translate debug language correctly yet.
> Translation Stubs Tool

- ModAssistant/Localisation/de.xaml
This issue closes #249 
- added all missing translation
- changed "About:List:Header" because it sounded awkward in german (it's still not 100% but I did't want to change the whole structure of the sentence)
(I'm native german)
> feat(249): added missing german translation

- ModAssistant/Localisation/fr.xaml
> :fr: Update translation

- ModAssistant/App.xaml.cs
- ModAssistant/Classes/External Interfaces/Playlists.cs
should close #208
it makes the folder if it cant find it
make any changes, if it doesnt compile at all ill just close it since im bad
> Check if Playlists folder exists before downloading

- ModAssistant/Localisation/sv.xaml
All credits for those translations go to Davy#0013 ( as I don't speak nor understand a single word of what's written here 😅 )
> Added/revised Swedish translations

- ModAssistant/MainWindow.xaml.cs
> [Fix] Spamming pat/hug buttons causes crashes

- ModAssistant/Localisation/de.xaml
- ModAssistant/Localisation/en.xaml
- ModAssistant/Localisation/fr.xaml
- ModAssistant/Localisation/it.xaml
- ModAssistant/Localisation/ko.xaml
- ModAssistant/Localisation/nl.xaml
- ModAssistant/Localisation/ru.xaml
- ModAssistant/Localisation/sv.xaml
- ModAssistant/Localisation/zh.xaml
Basically what the title says...
> Renamed the #support channelname to #pc-help

- ModAssistant/Localisation/fr.xaml
- ModAssistant/Localisation/nl.xaml
Exactly what the title states, this PR adds the missing translations for Dutch and French 😸
> Added missing translations for Dutch and French

- ModAssistant/Localisation/ko.xaml
Exactly what the title states, this PR adds the missing translations for Korean
> Added missing translations for Korean

- ModAssistant/Classes/Languages.cs
- ModAssistant/Localisation/nb.xaml
- ModAssistant/ModAssistant.csproj
A quick norwegian (bokmål) translation based off of the swedish one.
> Norwegian (bokmål) translation

- ModAssistant/Classes/Languages.cs
> Make availableLanguageCodes readonly

- ModAssistant/Localisation/nl.xaml
Fixed spelling mistakes and made the some translations a bit more readable.
> Updated nl.xaml

- ModAssistant/Localisation/de.xaml
- ModAssistant/Localisation/en.xaml
- ModAssistant/Localisation/fr.xaml
- ModAssistant/Localisation/it.xaml
- ModAssistant/Localisation/nb.xaml
- ModAssistant/Localisation/nl.xaml
- ModAssistant/Localisation/ru.xaml
- ModAssistant/Localisation/sv.xaml
- ModAssistant/Localisation/zh.xaml
- ModAssistant/Properties/AssemblyInfo.cs
- ModAssistant/Themes/BSMG.xaml
- ModAssistant/Themes/Dark.xaml
- ModAssistant/Themes/Light Pink.xaml
- ModAssistant/Themes/Light.xaml
- ModAssistant/Themes/Ugly Kulu-Ya-Ku.xaml
- README.md
As per discussion for the BSMG Wiki, Assistant decided the correct name should be Mod Assistant, hence all my changes in this PR.
> Fixed inconsistent naming ModAssistant vs Mod Assistant

- ModAssistant/Localisation/de.xaml
Exactly what the title says. I added 2 missing German translations.
> add missing German translations

- ModAssistant/Classes/External Interfaces/BeatSaver.cs
- Fixed bug resulting from inconsistent use of UTC and local time.
- Changed displayed time to local time to avoid confusion.
Closes #284
> Fixed rate limiting issues for playlists

- ModAssistant/Localisation/es.xaml
Hi, i have created a spanish translation, here it is:
I have to upload it as txt but in fact it is a xaml
[es.txt](https://github.com/Assistant/ModAssistant/files/6435700/es.txt)
> Spanish Translation created

- ModAssistant/MainWindow.xaml
- ModAssistant/Pages/About.xaml
- ModAssistant/Pages/Intro.xaml
- ModAssistant/Pages/Invalid.xaml
- ModAssistant/Pages/Options.xaml
Wraps the Grid objects with a ScrollViewer.
The scrollbar will only appear when needed.
All other changes are just auto formatting.
https://user-images.githubusercontent.com/27714637/118077823-c1d79080-b369-11eb-8759-63040847a571.mp4
> Add ScrollViewer for non Mod pages

- ModAssistant/Pages/Mods.xaml.cs
Reasoning: [PlaylistManager](https://github.com/rithik-b/PlaylistManager) is a core mod now and a replacement for PlaylistCore
> Added PlaylistManager as a default mod

- README.md
> work out things out = work things out

- ModAssistant/Classes/Languages.cs
- ModAssistant/Localisation/th.xaml
- ModAssistant/ModAssistant.csproj
- Completed Translation
Translated by: `Squishee`
> Added Localization/Translation for Thai Language (ภาษาไทย)

- ModAssistant/Localisation/th.xaml
- Fixed some misspelling in Thai
- Fixed some incorrect syntax like make it more understandable in Thai
> Fixed some incorrect syntax/misspelling in Thai

- ModAssistant/Classes/Languages.cs
- ModAssistant/Localisation/ja.xaml
- ModAssistant/ModAssistant.csproj
I used it as a reference: https://github.com/Assistant/ModAssistant/pull/283
> feat: Added Japanese localisation
